<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { invoke } from '@tauri-apps/api/core'
import { open, save as saveDialog } from '@tauri-apps/plugin-dialog'
import { Check, ChevronLeft, ChevronRight, Clipboard, Download, ExternalLink, FolderOpen, Play, Power, RefreshCw, RotateCw, Settings as SettingsIcon, Terminal, X } from '@lucide/vue'
import { formatUptime, statusTitle } from './model'

type Settings = { schemaVersion:number; configured:boolean; sharePath:string; bind:string; port:number; permissions:{browse:boolean;download:boolean;upload:boolean;archive:boolean;manage:boolean}; autostartApp:boolean; startService:boolean; keepInTray:boolean; openBrowser:boolean; theme:string }
type Status = { state:string; healthy:boolean; pid?:number; uptimeSeconds?:number; localUrl:string; lanUrls:string[]; message:string }
const defaults: Settings = { schemaVersion:1, configured:false, sharePath:'', bind:'127.0.0.1', port:5000, permissions:{browse:true,download:true,upload:true,archive:true,manage:false}, autostartApp:false,startService:true,keepInTray:true,openBrowser:false,theme:'system' }
const settings = ref<Settings>({...defaults, permissions:{...defaults.permissions}})
const persistedSettings = ref<Settings>({...defaults, permissions:{...defaults.permissions}})
const status = ref<Status>({state:'stopped',healthy:false,localUrl:'',lanUrls:[],message:'服务已停止'})
const pathInfo = ref<{exists:boolean;isDirectory:boolean;readable:boolean;writable:boolean;availableSpace?:number;warning?:string}|null>(null)
const loading = ref(true), busy = ref(false), error = ref(''), page = ref<'home'|'settings'|'logs'>('home'), step = ref(0), logs = ref('')
let timer:number|undefined
const steps=['欢迎','共享文件夹','网络配置','访问权限','启动选项','确认配置']
const isWizard=computed(()=>!settings.value.configured)
const stateText=computed(()=>statusTitle(status.value.state))
const uptime=computed(()=>formatUptime(status.value.uptimeSeconds))
async function call<T>(name:string,args?:Record<string,unknown>){return invoke<T>(name,args)}
async function refresh(){try{status.value=await call<Status>('service_status')}catch{}}
async function validateFolder(){pathInfo.value=settings.value.sharePath?await call('validate_path',{path:settings.value.sharePath}):null}
async function chooseFolder(){const result=await open({directory:true,multiple:false,title:'选择 Dufs 共享文件夹'}); if(typeof result==='string'){settings.value.sharePath=result;await validateFolder()}}
function formatBytes(value?:number){if(value===undefined)return '不可用';const units=['B','KB','MB','GB','TB'];let n=value,i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${units[i]}`}
async function next(){error.value=''; if(step.value===1){const v=await call<any>('validate_path',{path:settings.value.sharePath});if(!v.isDirectory||!v.readable){error.value='请选择存在且可读取的文件夹';return}} if(step.value===2){try{await call('check_port',{bind:settings.value.bind,port:settings.value.port})}catch(e){error.value=String(e);return}} step.value++}
async function finish(){busy.value=true;error.value='';try{settings.value.configured=true;await call('save_settings',{settings:settings.value});await call('start_service');persistedSettings.value=structuredClone(settings.value);await refresh();if(settings.value.openBrowser)await call('open_web')}catch(e){settings.value.configured=false;try{await call('save_settings',{settings:settings.value})}catch{}error.value=String(e)}finally{busy.value=false}}
async function action(name:string){busy.value=true;error.value='';try{status.value=await call<Status>(name)}catch(e){error.value=String(e)}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';const previous=structuredClone(persistedSettings.value),wasRunning=status.value.healthy;try{if(wasRunning)await call('stop_service');await call('save_settings',{settings:settings.value});if(wasRunning)await call('start_service');persistedSettings.value=structuredClone(settings.value);await refresh();page.value='home'}catch(e){try{await call('save_settings',{settings:previous});settings.value=structuredClone(previous);if(wasRunning)await call('start_service');persistedSettings.value=structuredClone(previous);await refresh()}catch(rollback){error.value=`${String(e)}；恢复旧配置失败：${String(rollback)}`;return}error.value=`新配置未能启动，已恢复旧配置：${String(e)}`}finally{busy.value=false}}
async function loadLogs(){logs.value=await call<string>('read_logs');page.value='logs'}
async function copy(text:string){await navigator.clipboard.writeText(text)}
async function exportLogs(){const path=await saveDialog({title:'导出运行日志',defaultPath:'dufs-desktop.log',filters:[{name:'日志文件',extensions:['log','txt']}]});if(path)await call('export_logs',{path})}
onMounted(async()=>{settings.value=await call<Settings>('get_settings');persistedSettings.value=structuredClone(settings.value);await refresh();loading.value=false;timer=window.setInterval(refresh,3000)})
onBeforeUnmount(()=>clearInterval(timer))
</script>

<template>
  <div v-if="loading" class="loading">正在读取本机配置...</div>
  <main v-else-if="isWizard" class="wizard-shell">
    <aside class="wizard-side"><div class="brand"><div class="logo">D</div><div><strong>Dufs 网盘</strong><small>桌面管理程序 1.0.1</small></div></div><ol><li v-for="(name,i) in steps" :class="{active:i===step,done:i<step}" :key="name"><span><Check v-if="i<step" :size="15"/><template v-else>{{i+1}}</template></span>{{name}}</li></ol></aside>
    <section class="wizard-main">
      <div class="wizard-content">
        <template v-if="step===0"><p class="eyebrow">首次使用</p><h1>欢迎使用 Dufs 网盘</h1><p class="lead">只需完成几个简单步骤，即可将本地文件夹共享到局域网。</p><div class="intro-list"><p><Check/>独立运行，无需安装 Node.js 或 Rust</p><p><Check/>支持 Windows、macOS 和 Linux</p><p><Check/>共享文件始终保留在你选择的本地目录</p></div></template>
        <template v-if="step===1"><h2>选择共享文件夹</h2><p class="muted">Dufs 只会在这个目录范围内提供文件服务。</p><label>文件夹路径</label><div class="path-row"><el-input v-model="settings.sharePath" placeholder="请选择已有文件夹" @blur="validateFolder"/><el-button :icon="FolderOpen" @click="chooseFolder">浏览</el-button></div><div v-if="pathInfo" class="path-status"><span :class="{ok:pathInfo.exists}">存在 {{pathInfo.exists?'是':'否'}}</span><span :class="{ok:pathInfo.readable}">可读 {{pathInfo.readable?'是':'否'}}</span><span :class="{ok:pathInfo.writable}">可写 {{pathInfo.writable?'是':'否'}}</span><span>可用空间 {{formatBytes(pathInfo.availableSpace)}}</span></div><el-alert :title="pathInfo?.warning||'请避免共享系统根目录、用户配置目录或包含敏感信息的位置。'" type="warning" :closable="false"/></template>
        <template v-if="step===2"><h2>网络配置</h2><p class="muted">选择谁可以访问网盘，并设置服务端口。</p><label>访问范围</label><el-radio-group v-model="settings.bind" class="choice-grid"><el-radio-button value="127.0.0.1">仅本机访问</el-radio-button><el-radio-button value="0.0.0.0">可信局域网访问</el-radio-button></el-radio-group><label>监听端口</label><el-input-number v-model="settings.port" :min="1" :max="65535" controls-position="right"/><el-alert v-if="settings.bind==='0.0.0.0'" title="同一网络中的设备可能访问此服务，请仅在可信网络中启用。" type="warning" :closable="false"/></template>
        <template v-if="step===3"><h2>文件访问权限</h2><p class="muted">权限由 Dufs 服务端强制执行，不只是隐藏界面按钮。</p><div class="switch-list"><div><b>浏览与下载</b><small>文件服务的基础只读能力</small><el-switch :model-value="true" disabled/></div><div><b>上传和创建文件夹</b><small>允许向共享目录添加内容</small><el-switch v-model="settings.permissions.upload"/></div><div><b>打包下载文件夹</b><small>允许生成流式 ZIP 下载</small><el-switch v-model="settings.permissions.archive"/></div><div><b>删除、覆盖和移动</b><small>Dufs 底层将这些写操作作为同一管理权限</small><el-switch v-model="settings.permissions.manage"/></div></div></template>
        <template v-if="step===4"><h2>启动与系统选项</h2><div class="switch-list"><div><b>启动应用时自动开启服务</b><small>配置有效时在后台启动 Dufs</small><el-switch v-model="settings.startService"/></div><div><b>登录系统时启动应用</b><small>默认关闭，可随时在设置中修改</small><el-switch v-model="settings.autostartApp"/></div><div><b>关闭窗口后保持后台运行</b><small>可从系统托盘重新打开或完全退出</small><el-switch v-model="settings.keepInTray"/></div><div><b>配置完成后打开网盘</b><small>使用系统默认浏览器打开本地地址</small><el-switch v-model="settings.openBrowser"/></div></div></template>
        <template v-if="step===5"><h2>确认配置</h2><div class="summary"><div><span>共享文件夹</span><b>{{settings.sharePath}}</b></div><div><span>访问范围</span><b>{{settings.bind==='0.0.0.0'?'可信局域网':'仅本机'}}</b></div><div><span>服务端口</span><b>{{settings.port}}</b></div><div><span>上传 / 管理</span><b>{{settings.permissions.upload?'允许':'禁止'}} / {{settings.permissions.manage?'允许':'禁止'}}</b></div><div><span>后台 / 开机启动</span><b>{{settings.keepInTray?'开启':'关闭'}} / {{settings.autostartApp?'开启':'关闭'}}</b></div></div></template>
        <el-alert v-if="error" :title="error" type="error" :closable="false"/>
      </div>
      <footer><el-button v-if="step>0" :icon="ChevronLeft" @click="step--">返回</el-button><span></span><el-button v-if="step<5" type="primary" @click="step===0?step++:next()">{{step===0?'开始配置':'继续'}}<ChevronRight :size="16"/></el-button><el-button v-else type="primary" :loading="busy" @click="finish">完成配置并启动</el-button></footer>
    </section>
  </main>
  <main v-else class="app-shell">
    <aside class="nav"><div class="brand"><div class="logo">D</div><div><strong>Dufs 网盘</strong><small>桌面管理</small></div></div><button :class="{active:page==='home'}" @click="page='home'"><Power/>服务状态</button><button :class="{active:page==='settings'}" @click="page='settings'"><SettingsIcon/>设置</button><button :class="{active:page==='logs'}" @click="loadLogs"><Terminal/>运行日志</button><div class="version">桌面版 1.0.1<br/>Dufs 内核 0.46.0</div></aside>
    <section class="workspace">
      <template v-if="page==='home'"><header><div><p class="eyebrow">服务中心</p><h1>{{stateText}}</h1></div><span class="status-pill" :class="status.state"><i/>{{status.message}}</span></header><div class="notice" v-if="error"><X/>{{error}}</div><div class="status-band"><div><span>本地访问地址</span><b>{{status.localUrl}}</b></div><div><span>运行时间</span><b>{{status.healthy?uptime:'--'}}</b></div><div><span>进程 ID</span><b>{{status.pid||'--'}}</b></div></div><div class="toolbar"><el-button v-if="!status.healthy" type="primary" :icon="Play" :loading="busy" @click="action('start_service')">启动服务</el-button><el-button v-else :icon="Power" :loading="busy" @click="action('stop_service')">停止</el-button><el-button :icon="RotateCw" :disabled="!status.healthy" @click="action('restart_service')">重启</el-button><el-button :icon="ExternalLink" :disabled="!status.healthy" @click="call('open_web')">打开网盘</el-button><el-button :icon="FolderOpen" @click="call('open_share_folder')">打开文件夹</el-button></div><section class="detail"><h2>当前配置</h2><dl><dt>共享目录</dt><dd>{{settings.sharePath}}</dd><dt>监听地址</dt><dd>{{settings.bind}}:{{settings.port}}</dd><dt>局域网地址</dt><dd v-if="status.lanUrls.length"><span v-for="url in status.lanUrls" :key="url" class="url">{{url}} <button title="复制地址" @click="copy(url)"><Clipboard/></button></span></dd><dd v-else>未开放局域网访问</dd><dt>文件权限</dt><dd>上传 {{settings.permissions.upload?'允许':'禁止'}}，管理 {{settings.permissions.manage?'允许':'禁止'}}</dd></dl></section></template>
      <template v-if="page==='settings'"><header><div><p class="eyebrow">本机设置</p><h1>服务配置</h1></div></header><div class="form"><label>共享文件夹</label><div class="path-row"><el-input v-model="settings.sharePath"/><el-button :icon="FolderOpen" @click="chooseFolder"/></div><label>访问范围</label><el-segmented v-model="settings.bind" :options="[{label:'仅本机',value:'127.0.0.1'},{label:'可信局域网',value:'0.0.0.0'}]"/><label>端口</label><el-input-number v-model="settings.port" :min="1" :max="65535"/><div class="switch-list compact"><div><b>允许上传</b><el-switch v-model="settings.permissions.upload"/></div><div><b>允许目录打包下载</b><el-switch v-model="settings.permissions.archive"/></div><div><b>允许删除、覆盖和移动</b><el-switch v-model="settings.permissions.manage"/></div><div><b>登录系统时启动应用</b><el-switch v-model="settings.autostartApp"/></div><div><b>关闭窗口后后台运行</b><el-switch v-model="settings.keepInTray"/></div></div><el-alert title="服务相关设置会在下次启动或重启服务后生效。" type="info" :closable="false"/><el-button type="primary" :loading="busy" @click="save">保存设置</el-button></div></template>
      <template v-if="page==='logs'"><header><div><p class="eyebrow">诊断</p><h1>运行日志</h1></div><div><el-button :icon="Clipboard" @click="copy(logs)">复制</el-button><el-button :icon="Download" @click="exportLogs">导出</el-button><el-button :icon="RefreshCw" @click="loadLogs">刷新</el-button><el-button :icon="FolderOpen" @click="call('open_log_folder')">打开位置</el-button></div></header><pre class="logs">{{logs||'暂无日志'}}</pre></template>
    </section>
  </main>
</template>
