/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/AppShell.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    DirectoryTree: typeof import('./components/DirectoryTree.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileDetailsTable: typeof import('./components/FileDetailsTable.vue')['default']
    FileGrid: typeof import('./components/FileGrid.vue')['default']
    FilePreview: typeof import('./components/FilePreview.vue')['default']
    OfficePreview: typeof import('./components/preview/OfficePreview.vue')['default']
    PdfPreview: typeof import('./components/preview/PdfPreview.vue')['default']
    RecentFiles: typeof import('./components/RecentFiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    StorageOverview: typeof import('./components/StorageOverview.vue')['default']
    TextPreview: typeof import('./components/preview/TextPreview.vue')['default']
    UploadManager: typeof import('./components/UploadManager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
